[package]
name = "coeus-python"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "coeus_python"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.16.5", features = ["extension-module", "abi3-py37"] }
coeus = {version = "0.1.1", path = "../coeus"}
regex = "1.6.0"
rayon = "1.5.3"
serde_json = "1.0.82"
